export interface InfoPagina{

    // Generated by https://quicktype.io

    titulo?:         string;
    email?:          string;
    nombre_corto?:   string;
    pagina_autor?:   string;
    facebook?:       string;
    twitter?:        string;
    instagram?:      string;
    tmblr?:          string;
    equipo_trabajo?: any[];
}

    


